### ISSUE TITLE
Missing handling of low level graphiclib

### ISSUE THREAD

**Issue by lbrulet** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#8]
I was trying to implement the ncruses lib, and I noticed that something is missing.
There is no sprite in ncruses, so I would like to create a subClass for the PixelPox named Pixel including a char and its color

**Comment by Hirevo** [comment]
We were thinking about exposing a putPixel method on the IGraphicLib who would take values from 0 to 100 and place the pixel in the right place depending of the current window size.
But maybe in the ncurses case, we could display a character who is highlighted of his own color to get a uniformly colored rectangle so that it can be expressed as a PixelBox.

**Comment by thibautcornolti** [comment]
putPixel seems to be a good means to resolve the issue. However, we should be able to choose either percent or absolute value (since we have the size of the window).
Another thing missing: the distinction between the background color and the text color.

**Comment by Hirevo** [comment]
Maybe we could implement both a relative and a absolute one, and let the game library decide which is more appropriate for its purposes.

**Comment by Hirevo** [comment]
As for the background color, maybe a clear method could be a solution ?

**Comment by thibautcornolti** [comment]
Method that would look to?
Just a `setBackgroundColor`?

**Comment by Hirevo** [comment]
It seems that all of these issues are being addressed separately.
If an issue mentioned here isn't solved, please re-submit it in its own issue or PR.
I'm closing this thread for now.
